/*! Generated by redux-scfld not for editing */

// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_APP = 'app';
export const NAMESPACE_POST = 'post';
export const NAMESPACE_POSTS = 'posts';

export const NAMESPACES = [
  NAMESPACE_APP,
  NAMESPACE_POST,
  NAMESPACE_POSTS,
];
// Generated Types
export const APP_LOAD = 'APP_LOAD';
export const POST_LOAD = 'POST_LOAD';
export const POSTS_LOAD = 'POSTS_LOAD';
